baseURL = 'https://stapp-hb-dfab.azurestaticapps.net/'
languageCode = 'en-us'
title = 'The Exploration of Modern Fabrication Techniques with Carbon Fibre and Metal through Bikes'
theme = 'hb-theme'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This allows us to embed the 3D Model Viewer later

[menu]
  [[menu.main]]
    name = 'Research'
    url = '/docs/'
    weight = 1
  [[menu.main]]
    name = 'Portfolio'
    url = '/projects/'
    weight = 2